version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: questlife-postgres
    environment:
      POSTGRES_DB: questlife
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: